aws_region = "us-east-1"
key_pair_name = "barath_mac_pair"
instance_type = "t2.micro"
ami = "ami-0c6b1d09930fac512"
node_name = "demo-java-docker"
ssh_connection_user="ec2-user"
security_group_name="demo-java-security-group"