#!/bin/bash

yum update -y
yum install -y git java-1.8.0-openjdk-devel docker
systemctl start docker
curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
