#!/bin/bash

yum update -y
yum install -y docker
systemctl start docker
curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
docker run --name nginx -p 8080:80 nginx
