aws_region = "us-east-1"
user="ec2-user"
private_key_path = ""
docker_repository_url="docker.io"
docker_repository_name = "barathece91"
template_source_path = "./templates/docker_build.tpl"
template_destination_path ="/home/ec2-user/docker_build"