aws_region = "us-east-1"
vpc_cidr = "11.0.0.0/16"
public_subnet_cidr_a = "11.0.0.0/24"
private_subnet_cidr_a = "11.0.1.0/24"
vpc_name = "client-vpc"
private_client_aws_route_table= "private_client_route_table"
public_client_aws_route_table = "public_client_route_table"
aws_internet_gateway_name = "client-internet-gateway"